config/routes.rb
Rails.application.routes.draw do
  get '/cart', to: 'page#cart'
  get 'page/show'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)

  resources :page, only: [:show]
  resources :category, only: [:index, :show]
  resources :product, only: [:index, :show] do
    member do
      post :add_to_cart
      post :change_item_quantity
      post :remove_item_from_cart
    end

    collection do
      post :clear_cart
    end
  end

  resources :search, only: [:index] do
    collection do
       get 'results'
    end
  end

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root to: 'product#index'
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # frozen_string_literal: true
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  # frozen_string_literal: true
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  # frozen_string_literal: true
  has_many :products
  validates :name, presence: true
  validates :name, uniqueness: true
end

app/models/order.rb
class Order < ApplicationRecord
  # frozen_string_literal: true
  belongs_to :user
  belongs_to :transaction_status
  has_many :product_in_orders
  has_many :products, through: :product_in_orders
end

app/models/page.rb
class Page < ApplicationRecord
  # frozen_string_literal: true
end

app/models/product.rb
class Product < ApplicationRecord
  # frozen_string_literal: true
  mount_uploader :image, ImageUploader
  belongs_to :category
  has_many :product_in_orders
  has_many :orders, through: :product_in_orders
  validates :name, :price, presence: true
  validates :price, numericality: true
end

app/models/product_in_order.rb
class ProductInOrder < ApplicationRecord
  # frozen_string_literal: true
  belongs_to :product
  belongs_to :order
end

app/models/province.rb
class Province < ApplicationRecord
  # frozen_string_literal: true
  has_many :users
  validates :name, :tax_rate, presence: true
  validates :name, uniqueness: true
  validates :tax_rate, :gst, :hst, numericality: true
end

app/models/transaction_status.rb
class TransactionStatus < ApplicationRecord
  # frozen_string_literal: true
  has_many :orders
end

app/models/user.rb
class User < ApplicationRecord
  # frozen_string_literal: true
  belongs_to :province
  has_many :orders
  validates :name, :email, :address, presence: true
  validates :email, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # frozen_string_literal: true
  helper_method :categories
  helper_method :pages
  before_action :initialize_session

  def categories
    @all_categories = Category.all
  end

  def pages
    @all_pages = Page.all
  end

  def initialize_session
    session[:cart] ||= []
  end

  def load_cart
    @cart = Product.find(session[:cart])
  end
end

app/controllers/category_controller.rb
class CategoryController < ApplicationController
  # frozen_string_literal: true

  def index
    @category_collection = Category.all
  end

  def show
    @category = Category.find(params[:id])
    @products = @category.products
  end
end

app/controllers/page_controller.rb
class PageController < ApplicationController
  # frozen_string_literal: true

  def show
    @page = Page.find(params[:id])
  end
end

app/controllers/product_controller.rb
class ProductController < ApplicationController
  # frozen_string_literal: true

  def index
    @product_collection = Product.all.page(params[:page]).per(2)
  end

  def show
    @product = Product.find(params[:id])
  end

  def add_to_cart
    @id = params[:id].to_i
    @product_to_add = Product.find(@id)
    session[:cart].each do |product|
      if product['id'] == @id
        @product_found = true
      end
    end
    unless @product_found
      session[:cart] << { id: @id, name: @product_to_add.name, price: @product_to_add.price, quantity: 1 }
    end
    redirect_to root_url
  end

  def remove_item_from_cart
    remove_item
    redirect_to '/cart'
  end

  def change_item_quantity
    @id = params[:id].to_i
    session[:cart].each do |product|
      if params[:teste].to_i <= 0
        remove_item
      elsif product['id'] == @id
        product['quantity'] = params[:teste].to_i
      end
    end
    redirect_to '/cart'
  end

  def clear_cart
    session[:cart] = []
    redirect_to root_url
  end

  private

  def remove_item
    @id = params[:id].to_i
    session[:newCart] = []
    session[:cart].each do |product|
      unless product['id'] == @id
        session[:newCart] << product
      end
    end
    session[:cart] = session[:newCart]
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  # frozen_string_literal: true

  def index
    @categories = Category.all
  end

  def results
    @categories = Category.all
    @teste = params[:q]

    if params[:c] == '' && params[:q] == ''
      @products = Product.all
    elsif params[:c] == ''
      @products = Product.where('name LIKE ? OR description LIKE ?', "%#{@teste}%", "%#{@teste}%")
    else
      @category = Category.find(params[:c])
      @products = Product.where(category_id: @category.id)
      @products = @products.where('name LIKE ? OR description LIKE ?', "%#{@teste}%", "%#{@teste}%")
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/category_helper.rb
module CategoryHelper
end

app/helpers/page_helper.rb
module PageHelper
end

app/helpers/product_helper.rb
module ProductHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/views/category/index.html.erb
<h2>Categories available</h2>
<ul>
  <% @category_collection.each do |category| %>
    <li><%= link_to category.name, category %></li>
  <% end %>
</ul>

app/views/category/show.html.erb
<p>Products in the selected category:</p>

<ul>
  <% @products.each do |product| %>
    <li><%= link_to product.name, product %></li>
  <% end %>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>EcommerceProject</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <h1>Generic Store</h1>
    </header>
    <ul>
      <% categories.each do |category| %>
        <li> <%= link_to category.name, category %></li>
      <% end %>
      <% pages.each do |page| %>
        <li> <%= link_to page.name.capitalize!, page %></li>
      <%end%>
    </ul>
    <ul>
      <li><%= link_to "Products", root_path %></li>
      <li><%= link_to "Search", search_index_path %></li>
      <li> <%= link_to "Shopping Cart", '/cart' %></li>
    </ul>
    <%= yield %>
  </body>
</html>

app/views/page/cart.html.erb
<h2>Cart</h2>
<%= debug session[:cart] %>

<h2>Products in the cart:</h2>
<ul>
<% session[:cart].each do |product| %>
  <li><%= link_to product["name"], product_path(product["id"]) %></li>
  <%= form_tag(change_item_quantity_product_path(product["id"]), method: "post") do %>
    <%= label_tag(:teste, "Change quantity:") %>
    <%= text_field_tag(:teste) %>
    <%= submit_tag("Confirm") %>
  <% end %>
  <li><%= link_to "Remove", remove_item_from_cart_product_path(product["id"]), method: :post %></li>
<% end %>
<p><%= link_to "Clear cart", clear_cart_product_index_path, method: :post %></p>
</ul>

app/views/page/show.html.erb
<h2><%= @page.name.capitalize! %></h2>

<p><%= @page.content %></p>

app/views/product/index.html.erb
<h2>Cart</h2>
<%= debug session[:cart] %>
<p><%= link_to "Clear cart", clear_cart_product_index_path, method: :post %></p>

<h2>Available products</h2>
<ul>
<% @product_collection.each do |product| %>
  <li><%= link_to product.name, product %></li>
  <li><%= link_to "Add to cart", add_to_cart_product_path(product), method: :post %></li>
  <li><%= link_to "Remove", remove_item_from_cart_product_path(product), method: :post %></li>
<% end %>
</ul>

<%= paginate @product_collection %>

app/views/product/show.html.erb
<h2>More about the product</h2>
<ul>
  <li>Name: <%= @product.name %></li>
  <li>Price: CAD <%= @product.price %></li>
  <li>Description: <%= @product.description %></li>
  <% if @product.image.present? %>
    <li><%= image_tag @product.image.url %></li>
  <% end %>
  <li>Category: <%= link_to @product.category.name, @product.category %></li>
</ul>

app/views/search/index.html.erb
<h2>Search by category</h2>

<%= form_tag(results_search_index_path, method: "get") do %>
  <%= select_tag(:c, options_for_select(@categories.collect {|p| [ p.name, p.id ] }), include_blank: true) %>
  <%= label_tag(:q, "Search for:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>

app/views/search/results.html.erb
<% if @category.nil? %>
  <h2>List of all products for all categories: </h2>
  <ul>
  <% @products.each do |product| %>
    <li><%= link_to product.name, product %></li>
  <% end %>
  </ul>
<% else %>
  <h2>Products Found for category "<%= @category.name %>":</h2>
  <h2>Amount of different Products <%= @products.count %>.</h2>
  <ul>
  <% @products.each do |product| %>
    <li><%= link_to product.name, product %></li>
  <% end %>
  </ul>
<% end %>